# Generated by Django 4.1 on 2023-09-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="cart_id",
            field=models.CharField(blank=True, default="", max_length=250, null=True),
        ),
    ]
